services:
  nginx:
    container_name: butecodosdevs_nginx
    image: nginx:latest
    ports:
      - 8080:80
    volumes:
      - ./docker/nginx-default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/php.ini:/usr/local/etc/php/conf.d/php.ini
      - ./wordpress:/var/www/html
    depends_on:
      - php

  php:
    container_name: butecodosdevs_php
    build:
      context: .
      dockerfile: ./docker/php.dockerfile
    volumes:
      - ./wordpress:/var/www/html
    depends_on:
      - mysql

  mysql:
    container_name: butecodosdevs_mysql
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: butecodosdevs
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./database/mysql:/var/lib/mysql

  phpmyadmin:
    container_name: butecodosdevs_phpmyadmin
    image: phpmyadmin
    ports:
      - 8081:80
    environment:
      - PMA_ARBITRARY=1
      - UPLOAD_LIMIT=2048M

volumes:
  butecodosdevs_wordpress: